### ISSUE TITLE
 cannot load such file -- byebug (LoadError)

### ISSUE THREAD

**Issue by mensfeld** [listminut/use_cases#3]
Hey,

When trying to use this lib I get:

```ruby
`require': cannot load such file -- byebug (LoadError)
\tfrom /app/vendor/bundle/ruby/2.7.0/gems/use_cases-0.3.1/lib/use_cases/notifications.rb:3:in `'
\tfrom /app/vendor/bundle/ruby/2.7.0/gems/use_cases-0.3.1/lib/use_case.rb:17:in `require'
\tfrom /app/vendor/bundle/ruby/2.7.0/gems/use_cases-0.3.1/lib/use_case.rb:17:in `'
\tfrom /app/vendor/bundle/ruby/2.7.0/gems/use_cases-0.3.1/lib/use_cases.rb:3:in `require_relative'
\tfrom /app/vendor/bundle/ruby/2.7.0/gems/use_cases-0.3.1/lib/use_cases.rb:3:in `'
```

It seems byebug ain't part of deps.

Also on top of that, the long run for `dry-transaction` is to be deprecated and not maintained: https://github.com/dry-rb/dry-transaction/issues/127

Not sure if you should bet your libs on it.

**Comment by guilherme-andrade** [comment]
Hey @mensfeld , thanks for the report, we had only been using the gem in development mode up until today.

I've fixed this in the meantime, and it should be ok in versions `> 0.3.3`.

And thanks for sharing your thoughts on our implementation of `dry-transation`. We were aware of the discussion, but preferred internally to opt for it's implementation over the do-notation alone.

Also, I might be wrong, but the later comments in the thread appear to say that there will be maintenance of the gem, as soon as someone offers to refactor it into the do-notation. Thus the comment up top:
> Original description that's now obsolete.
